### ISSUE TITLE
Include international NKOS workshops

### ISSUE THREAD

**Issue by nichtich** [PhilippMayr/NKOS-bibliography#9]
http://nkos.slis.kent.edu/ lists more workshops in addition to European NKOS.

**Comment by PhilippMayr** [comment]
here are some US workshops

The 10th NKOS Workshop, "Semantic Search: Magnet for the Needle in the Search Haystack", a Joint NKOS-CENDI Workshop, December 6, 2012, DOT Media Center, U.S. Department of Transportation, Washington DC.
The 9th NKOS Workshop, "Knowledge Organization Systems: Managing Toward the Future", a Joint CENDI/NKOS Workshop, October 22, 2009, The National Agricultural Library, Beltsville, MD. 
The 8th NKOS Workshop "New Dimensions in Knowledge Organization Systems", a Joint NKOS/CENDI Workshop, September 11, 2008, The World Bank, Washington, DC. 
The 7th NKOS workshop "Next Generation Knowledge Organization Systems: Integration Challenges and Strategies" at JCDL 2005 June 10 and 11, Denver. 
The 6th NKOS Workshop "Building a Meaningful Web: From Traditional Knowledge Organization Systems to New Semantic Tools" at 2003 Joint Conference on Digital Libraries (JCDL), May 31, 2003, Houston, TX. Workshop summary by Dagobert Soergel (ppt) was presented at the ECDL02 NKOS Workshop. 
The 5th NKOS Workshop "Digital gazetteers Integration into distributed digital library services" at the 2002 Joint Conference on Digital Libraries, July 18th, Portland, Oregon. Workshop Summary (WORD file)
The 4th NKOS Workshop "Classification Crosswalks: Bringing Communities Together" at the First ACM+IEEE Joint Conference on Digital Libraries (JCDL) on June 28th, 2001 in Roanoke, VA. 
The 3rd NKOS Workshop at the 2000 ACM Digital Libraries Conference in San Antonio, Wednesday June 7th.
The 2nd NKOS Workshop at the 1999 ACM Digital Libraries Conference in Berkeley, Saturday August 14th 
NKOS Workshops at the 1998 and 1997 ACM Digital Libraries Conferences: description of the workshop and notes from the workshop.
